apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo
spec:
  generators:
    - list:
        elements:
          - customer: foo
          - customer: bar
          - customer: abc
          - customer: def
  template:
    metadata:
      name: 'demo-{{customer}}'
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
    spec:
      project: demo
      source:
        repoURL: https://github.com/pamelia/demo-ops.git
        targetRevision: HEAD
        path: "charts/demo"
        helm:
          releaseName: "demo"
          valueFiles:
            - "values.yaml"
            - "../../values/{{customer}}/demo/values.yaml"
      destination:
        server: https://kubernetes.default.svc
        namespace: 'demo-{{ customer }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
